version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://poudelanil658:anil1234@ecom.x00es.mongodb.net
    volumes:
      - .:/app
      - /app/node_modules
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
